---
title: "Window Lists"
output:
  html_document:
    theme: simplex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE}
get_lists <- function(region, observer) {
  lists_data <-
    xml2::read_html(sprintf("https://ebird.org/region/%s/activity", region))
  lists_data <- rvest::html_node(lists_data, "#place-main-content-results")
  obsvrs <- trimws(rvest::html_text(rvest::html_nodes(lists_data, "h3")))
  lists <-
    rvest::html_nodes(lists_data, "a.Meta-label")[obsvrs == observer]
  lists <- rvest::html_attr(lists, "href")
  lists <- stats::setNames(as.list(lists), basename(lists))
  if (length(lists)) {
    for (i in basename(unlist(lists))) {
      if (i %in% list.files(paste0("lists/", observer))) {
        next
      } else {
        lists[[i]] <- xml2::read_html(paste0("https://ebird.org/checklist/", i))
        comments <- rvest::html_text(rvest::html_nodes(lists[[i]], ".u-stack-xs"))
        if (any(grepl("HWL", toupper(comments)))) {
          lists[[i]] <-
            rvest::html_text(rvest::html_nodes(lists[[i]], "li .Heading-main"))
          writeLines(lists[[i]], paste("lists", observer, i, sep = "/"))
        } else {
          writeLines("", paste("lists", observer, i, sep = "/"))
        }
      }
    }
  }
}

get_lists("AU-VIC-MOR", "Michael  Livingston")
get_lists("FI-18", "Will Morris")
get_lists("AU-QLD-BRI", "Natasha Cadenhead")

wm <- lapply(list.files("lists/Will Morris", full.names = TRUE), readLines)
wm <- unlist(wm)
wm <- unique(wm)
wm <- wm[!!nchar(wm)]
wm <- rev(wm)

ml <- lapply(list.files("lists/Michael  Livingston", full.names = TRUE), readLines)
ml <- unlist(ml)
ml <- unique(ml)
ml <- ml[!!nchar(ml)]
ml <- rev(ml)

nc <- lapply(list.files("lists/Natasha Cadenhead", full.names = TRUE), readLines)
nc <- unlist(nc)
nc <- unique(nc)
nc <- nc[!!nchar(nc)]
nc <- rev(nc)

tab <- matrix("", max(length(wm), length(ml), length(nc)), 3)
tab[1, ] <- c(length(wm), length(ml), length(nc)) - 1
tab[seq(1, length(wm)), 1] <- wm
tab[seq(1, length(ml)), 2] <- ml
tab[seq(1, length(nc)), 3] <- nc
```

```{r, echo = FALSE}
knitr::kable(
  tab,
  col.names = paste(c("WM", "ML", "NC"), c(length(wm), length(ml), length(nc)), sep = ": ")
)
```

